/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.lms;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
      Scanner Keyboard = new Scanner(System.in);
      
      
      
      System.out.print("번호?");
      int no = Keyboard.nextInt();
      
      
      System.out.print("수업명?");
      String classname = Keyboard.next();
      
      System.out.print("수업내용?");
      String title = Keyboard.next();
      
      System.out.print("시작일?");
      String start = Keyboard.next();
      
      System.out.print("종료일?");
      String end = Keyboard.next();
      
      System.out.print("총수업시간?");
      String time = Keyboard.next();
      
      System.out.print("일수업시간?");
      String outtime = Keyboard.next();
      
      System.out.printf("번호 %d\n ", no);
      System.out.printf("수업명: %s\n", classname );
      System.out.printf("수업내용? %s\n", title );
      System.out.printf("기간 %s ~ %s\n" , start , end);
      System.out.printf("종료일? %d\n", end );
      System.out.printf("총수업시간? %d\n", time);
      System.out.printf("일수업시간? %d\n", outtime);
      
      
      
      
      
    }
}
